In [97]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn import linear_model as lm

In [98]:
x_1 = np.random.uniform(10,40,100)
x_2 = np.random.uniform(-50,20,100)
x_3 = np.random.uniform(20,60,100)
x_4 = np.random.uniform(10,40,100)
x_5 = np.random.uniform(-50,20,100)
x_6 = np.random.uniform(20,60,100)
epsilon = np.random.normal(0,10,100)

In [99]:
y=-30+0.4*x_1+3.4*x_2+5.9*x_3-0.2*x_4+0.6*x_5-1.8*x_6+epsilon

In [100]:
X_ols=pd.DataFrame()
X_ols['Constant']=pd.Series(np.ones(100))
X_ols['X1'] = pd.Series(x_1)
X_ols['X2'] = pd.Series(x_2)
X_ols['X3'] = pd.Series(x_3)
X_ols['X4'] = pd.Series(x_4)
X_ols['X5'] = pd.Series(x_5)
X_ols['X6'] = pd.Series(x_6)

In [101]:
model_reg = sm.OLS(y,X_ols).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.990
Model:                            OLS   Adj. R-squared:                  0.990
Method:                 Least Squares   F-statistic:                     1587.
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           2.43e-91
Time:                        20:39:11   Log-Likelihood:                -365.73
No. Observations:                 100   AIC:                             745.5
Df Residuals:                      93   BIC:                             763.7
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -24.2630      7.132     -3.402      0.001     -38.425     -10.101
X1             0.5190      0.113      4.600      0.000       0.295       0.743
X2             3.4012      0.050     68.415      0.000       3.302       3.500
X3             5.7542      0.090     63.630      0.000       5.575       5.934
X4            -0.1859      0.126     -1.471      0.145      -0.437       0.065
X5             0.6345      0.051     12.488      0.000       0.534       0.735
X6            -1.8513      0.085    -21.801      0.000      -2.020      -1.683
==============================================================================
Omnibus:                        0.145   Durbin-Watson:                   2.223
Prob(Omnibus):                  0.930   Jarque-Bera (JB):                0.005
Skew:                          -0.010   Prob(JB):                        0.998
Kurtosis:                       3.026   Cond. No.                         519.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [102]:
# Now we add some unrelated coefficients
x_7 = np.random.uniform(10,40,100)
x_8 = np.random.uniform(-50,20,100)
x_9 = np.random.uniform(20,60,100)
x_10 = np.random.uniform(10,40,100)
x_11 = np.random.uniform(-50,20,100)
x_12 = np.random.uniform(20,60,100)

In [103]:
X_ext = pd.DataFrame()
X_ext['Constant']=pd.Series(np.ones(100))
X_ext['X1'] = pd.Series(x_1)
X_ext['X2'] = pd.Series(x_2)
X_ext['X3'] = pd.Series(x_3)
X_ext['X4'] = pd.Series(x_4)
X_ext['X5'] = pd.Series(x_5)
X_ext['X6'] = pd.Series(x_6)
X_ext['X7'] = pd.Series(x_7)
X_ext['X8'] = pd.Series(x_8)
X_ext['X9'] = pd.Series(x_9)
X_ext['X10'] = pd.Series(x_10)
X_ext['X11'] = pd.Series(x_11)
X_ext['X12'] = pd.Series(x_12)

In [104]:
model_reg = sm.OLS(y,X_ext).fit()
model_reg.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.991
Model:                            OLS   Adj. R-squared:                  0.990
Method:                 Least Squares   F-statistic:                     785.5
Date:                Mon, 02 Oct 2023   Prob (F-statistic):           3.55e-83
Time:                        20:39:11   Log-Likelihood:                -362.91
No. Observations:                 100   AIC:                             751.8
Df Residuals:                      87   BIC:                             785.7
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Constant     -23.8147      9.717     -2.451      0.016     -43.129      -4.501
X1             0.5142      0.116      4.425      0.000       0.283       0.745
X2             3.4200      0.051     66.676      0.000       3.318       3.522
X3             5.7471      0.093     61.812      0.000       5.562       5.932
X4            -0.2342      0.133     -1.766      0.081      -0.498       0.029
X5             0.6337      0.052     12.254      0.000       0.531       0.736
X6            -1.8959      0.091    -20.848      0.000      -2.077      -1.715
X7             0.2047      0.123      1.669      0.099      -0.039       0.449
X8            -0.0101      0.048     -0.213      0.832      -0.105       0.084
X9             0.0676      0.093      0.729      0.468      -0.117       0.252
X10            0.0100      0.114      0.088      0.930      -0.216       0.236
X11            0.0046      0.051      0.090      0.928      -0.097       0.106
X12           -0.1192      0.089     -1.338      0.185      -0.296       0.058
==============================================================================
Omnibus:                        2.050   Durbin-Watson:                   2.177
Prob(Omnibus):                  0.359   Jarque-Bera (JB):                1.483
Skew:                          -0.259   Prob(JB):                        0.476
Kurtosis:                       3.294   Cond. No.                         983.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [105]:
# When we input the matrix, we don't need to add the column of ones because \
# Lasso automatically takes it into account

X_ext = X_ext.drop(columns=['Constant'])
model_lasso = lm.Lasso(alpha=1).fit(X_ext,y)
model_lasso.coef_

array([ 5.01020672e-01,  3.41531011e+00,  5.74026077e+00, -2.13587758e-01,
        6.31785168e-01, -1.88383021e+00,  1.83944057e-01, -6.22133095e-03,
        5.82088829e-02,  0.00000000e+00,  1.22978868e-03, -1.08624458e-01])

In [106]:
model_lasso = lm.Lasso(alpha=10).fit(X_ext,y)
model_lasso.coef_

array([ 0.39760225,  3.37219303,  5.68824133, -0.0280617 ,  0.61478913,
       -1.78170329,  0.        ,  0.        ,  0.        , -0.        ,
       -0.        , -0.00988457])

In [107]:
# We now apply Ridge Regression to our data

model_ridge = lm.Ridge(alpha=10).fit(X_ext,y)
model_ridge.coef_

array([ 5.13811806e-01,  3.41894062e+00,  5.74210034e+00, -2.34301201e-01,
        6.33706700e-01, -1.89423559e+00,  2.03567532e-01, -9.71666196e-03,
        6.78298713e-02,  1.00952023e-02,  4.29474786e-03, -1.18979263e-01])

In [108]:
model_ridge = lm.Ridge(alpha=10000).fit(X_ext,y)
model_ridge.coef_

array([ 0.328229  ,  2.65976579,  3.08609587, -0.18626152,  0.57669037,
       -1.01078708, -0.12163021,  0.18727697,  0.13699585,  0.00615086,
       -0.11519853, -0.0047458 ])

In [109]:
model_ridge = lm.Ridge(alpha=100).fit(X_ext,y)
model_ridge.coef_

array([ 5.10672237e-01,  3.40952237e+00,  5.69737404e+00, -2.35547901e-01,
        6.33996771e-01, -1.87903298e+00,  1.93499979e-01, -5.91435149e-03,
        6.98242321e-02,  1.06629339e-02,  1.40527009e-03, -1.17397639e-01])

In [110]:
model_ridge = lm.Ridge(alpha=1000).fit(X_ext,y)
model_ridge.coef_

array([ 0.4824021 ,  3.3193123 ,  5.28641555, -0.242468  ,  0.63512031,
       -1.74041425,  0.11019616,  0.02851739,  0.08690758,  0.01409637,
       -0.02388878, -0.10176876])

In [111]:
model_ridge = lm.Ridge(alpha=100000).fit(X_ext,y)
model_ridge.coef_

array([ 0.08836724,  0.92805759,  0.60972294, -0.0365842 ,  0.21262605,
       -0.1889711 , -0.0692876 ,  0.15907635,  0.06356232, -0.00112112,
       -0.06082469,  0.03727716])